config/routes.rb
Rails.application.routes.draw do
  # root route
  root 'static_pages#home'
  get '/home', to: 'static_pages#home', as: 'home'
  get '/about', to: 'static_pages#about', as: 'about'
  get '/contact', to: 'static_pages#contact', as: 'contact'

  # sessions routes
  get '/signin', to: 'sessions#new'
  post '/sessions/create', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  # user routes
  get '/users', to: 'users#index'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/signup', to: 'users#new', as: 'new_user'

  # html pages templates
  get '/html/users', to: 'html#users_index'
  get '/html/user', to: 'html#users_show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates_presence_of :username, :experience, :credits
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user
  before_action :login_required, except: [:home, :new, :create]

  def logged_in?
    current_user
  end

  private

  def login_required
    redirect_to root_path unless logged_in?
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_path
    @current_path = request.env['PATH_INFO'].split("/")[1]
  end

  helper_method :current_user
  helper_method :current_path
end

app/controllers/html_controller.rb
class HtmlController < ApplicationController
  def users_index
  end

  def users_show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(username: params[:user][:username])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "You have successfully logged in"
    else
      redirect_to signin_path, alert: "Login failed, please try again"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @greeting = "Welcome to the website"
  end

  def about
    
  end

  def contact

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "You have successfully registered."
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :experience, :credits, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/html/users_index.html.erb
<h1 class="title">All Users</h1>

<ul>
  <li><a href="#">Bob Cobb</a></li>
  <li><a href="#">Hal Hope</a></li>
  <li><a href="#">Kal Kool</a></li>
  <li><a href="#">Val Vine</a></li>
</ul>

app/views/html/users_show.html.erb
<h1 class="title">User Detail</h1>

<h4>
  Username: bobcobb
</h4>

<p>
  Age: 34
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFullAppV1</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <!-- Navigation -->
    <nav class="navbar is-black" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href="<%= root_path %>">
          <%= image_tag('blog-logo-white.png', size: '28x28', alt: 'Full App Home') %>
        </a>

        <div class="navbar-burger" data-target="navMenu">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>
      <div class="navbar-menu" id="navMenu">
        <div class="navbar-start">
          <%= link_to 'Home', root_path, class: "navbar-item #{'is-active' if current_path.nil?}" %>
          <%= link_to 'About', about_path, class: "navbar-item #{'is-active' if current_path == 'about'}" %>
          <%= link_to 'Contact', contact_path, class: "navbar-item #{'is-active' if current_path == 'contact'}" %>
        </div>

        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <% if current_user %>
                <p class="control">
                  <%= link_to "Log Out", signout_path, method: :delete, class: 'button is-info' %>
                </p>
              <% else %>
                <p class="control">
                  <a href="<%= new_user_path %>" class="button is-info">
                    <span>Sign Up</span>
                  </a>
                </p>
                <p class="control">
                  <a href="<%= signin_path %>" class="button is-info">
                    <span>Sign In</span>
                  </a>
                </p>              
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>

    <div class="section">
      <div class="container">
        <%= yield %>
      </div>
    </div>

  </body>
</html>

app/views/shared/_flash.html.erb
<% flash.each do |name, message| %>
  <% if name == 'alert' %>
    <div class="notification is-danger">
      <%= message %>
    </div>
  <% elsif name == 'notice' %>
    <div class="notification is-success">
      <%= message %>
    </div>
  <% else %>
    <div class="notification is-primary">
      <%= message %>
    </div>
  <% end %>
<% end %>

app/views/static_pages/about.html.erb
<h1 class="title">About this Website</h1>

app/views/static_pages/contact.html.erb
<h1 class="title">Contact Us</h1>

app/views/static_pages/home.html.erb
<section class="section">
    <div class="container">
      <h1 class="title">
        <figure class="image is-48x48">
          <%= image_tag 'blog-logo.png' %>
        </figure>
        Hello World
      </h1>
      <p class="subtitle">
        <span class="icon">
         <%= fa_icon "home" %>
        </span>
        <%= @greeting %>
      </p>
    </div>
  </section>
  </body>
</html>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="errors_explanation">
    <h5 class="title is-5">
      <%= pluralize(@user.errors.count, "error") %> 
      prevented the user account from being saved.
    </h5>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li>
          <span class="icon has-text-danger">
            <%= fa_icon "ban" %>
          </span>
          <%= message %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @user do |f| %>
  <div class='field'>
    <%= f.label :username, class: 'label' %>
    <div class='control'>
      <%= f.text_field :username, class: 'input', placeholder: 'Username' %>
    </div>
  </div>

  <div class='field'>
    <%= f.label :password, class: 'label' %>
    <div class='control'>
      <%= f.password_field :password, class: 'input', placeholder: 'Password' %>
    </div>
  </div>

  <div class='field'>
    <%= f.label :experience, class: 'label' %>
    <div class='control'>
      <%= f.number_field :experience, class: 'input', placeholder: 'Experience in Years' %>
    </div>
  </div>

  <div class='field'>
    <%= f.label :credits, class: 'label' %>
    <div class='control'>
      <%= f.number_field :credits, class: 'input', placeholder: 'Credits in Whole Numbers' %>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <label class="checkbox">
        <%= f.check_box :admin %>
        Check is this is an admin account
      </label>
    </div>
  </div>

  <div class="field">
    <div class="control">
      <%= f.submit 'Submit', class: 'button is-info' %>
    </div>
  </div>  
<% end %>

app/views/users/index.html.erb
<h1 class="title">All Users</h1>

<h4 class="title is-4"><%= pluralize(@users.size, "user") %></h4>

<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.username, user_path(user) %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1 class="title">New User Form</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<nav class="breadcrumb has-succeeds-separator" aria-label="breadcrumbs">
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'All Users', users_path %></li>
    <li class="is-active"><a href="#" aria-current="page"><%= @user.username.capitalize %></a></li>
  </ul>
</nav>

<%= render 'shared/flash' %>

<h1 class="title">User Details</h1>

<h4>
  Username: <%= @user.username %>
</h4>

<p>
  Experience: <%= @user.experience %>
</p>

<p>
  Credits Remaining: <%= @user.credits %>
</p>

<p>
  Administrator? <%= @user.admin %>
</p>